using System;

namespace Package.Etermax.EterChallenge.Users.Domain.Errors
{
    public class IdentityAlreadyExists : Exception
    {
        public IdentityAlreadyExists() : base("Identity already exists.")
        {
        }
    }
}